### ISSUE TITLE
enhancement - add a way to return data along with markup

### ISSUE THREAD

**Issue by leeoniya** [malsup/taconite#1]
hi Mike,

it would be great to be able to return data along with the xml markup and scripts. the only way to do it now is to rely on some global variable and set it via &lt;eval&gt; (ewww). or parse it out using datafilters in the new ajax pipeline.

perhaps another reserved tag similar to &lt;eval&gt; like &lt;data type=""&gt; (text/csv, application/json, etc) with the parsed object passed to any 'taconite-complete-notify' callbacks.

if i was to get really carried away, i'd add the ability to register parsers into taconite for datatypes you expect to get back, including any custom ones you make up. eg: $.taconite.addDataParser('my/format', function(str){return str;});

i can fork, slap something together and do a pull request. what do you think?

thanks,
Leon

**Comment by malsup** [comment]
I like the idea of supporting raw data like this.  Perhaps like <csv>..</csv> or <json>...</json>.  Don't see the relevance of the taconite-complete-notify call though since that is triggered once for the entire command doc.  Registering custom handlers is a good idea too.  Cheers!

**Comment by malsup** [comment]
Actually, I think I like your idea better...  <data type="json">

**Comment by malsup** [comment]
Hmm, except that 'data' is an actually jQuery method so we'll need a diff name.  Maybe <rawData> or something.

**Comment by leeoniya** [comment]
i would say 'data' is okay to use. even though there's a $.data, it's not really usable via taconite since the first argument needs to be a DOM element and not something you can pass back from a server. $.fn.data is the one you can use as it takes a selector. rawData seems weird to me - it's no more raw than anything else.

**Comment by leeoniya** [comment]
oh, never mind. i rechecked the syntax, 'data' would map to $.fn.data. hmmm...so few synonyms for data in english.

**Comment by malsup** [comment]
Like any of these?

"custom", "noop", "plain", "notify", "textData", "unprocessed", "tdata"

Since the data will be unprocessed by taconite maybe "raw" or "rawData" are ok.

**Comment by leeoniya** [comment]
rawData works, keep it :). i still say change rawDataHandler to rawDataParser to emphasize a limited parse-and-return responsibility

**Comment by leeoniya** [comment]
implemented in v3.56
closed by 7467de9fa9a02bb5cec9855326cec391e09621ef
