### ISSUE TITLE
Proposed IE Fix

### ISSUE THREAD

**Issue by nyndesigns** [malsup/taconite#10]
**Proposed code modification (line 145):**

**From:**
if( ! xml ) {

**To:**
if (! ( xml && xml.documentElement) ) {

**Reason:**
In IE, during a call to pull content (including inline javascript referencing taconite - there is a reason I'm not using taconite to evaluate this code after it has loaded) over AJAX and load it within colorbox - IE would error out (Message: Object required | Line: 150 | Char: 3 | Code: 0). After much debugging - I noticed that taconite was attempting to process the entire html string after it was loaded into the browser. 

It would fail this test and convert the string to an object **as is expected** (starting at line 142):
    if (typeof xml == 'string')
        xml = convert(xml);

And then error out in IE a few lines down because xml.documentElement is null (line 150):
   var root = xml.documentElement.tagName;

Firefox, Safari, Opera and Chrome did not experience this error - however - by adding the simple test in the proposed fix, all browsers work. If required, I can supply an example (as I realize my explanation is quite concise and isolated).

**Comment by malsup** [comment]
Fixed.  Thank you.
