### ISSUE TITLE
Autodetect Taconite and strings in Ajax

### ISSUE THREAD

**Issue by galacticevil** [malsup/taconite#4]
There appears to be a problem when Taconite intercepts all Ajax calls, and the response data from the call is simply text (no html) or poorly formed html.
IE9 will throw a Syntax Error, and Firefox will report either the same or a 'junk after' error. I'm using the latest version of taconite (3.59) and jquery 1.5.2. The issue can be recreated below:

```
$.get('test.php', function(data) {
    alert(data);
});
```

And in the _test.php_ file:

```
<?php
echo 'test';
?> 
```

Now try the same test but change the _test.php_ file to get a different error :

```
<?php
echo '<em>Tested</em> again';
?>
```

I'm not sure if this is the correct way to fix it, but changing _line 95_ from :

```
if ((data && data.documentElement && data.documentElement.nodeName != 'parsererror') || typeof data == 'string') {
```

to :

```
if (data && data.documentElement && data.documentElement.nodeName != 'parsererror' && ct == 'text/xml') {
```

seems to fix the problem for me. Actual taconite calls work correctly in all cases.

**Comment by malsup** [comment]
Fixed in v3.60
