### ISSUE TITLE
enhancement: allow plugin that do not use select.

### ISSUE THREAD

**Issue by gops** [malsup/taconite#5]
e.g. something like below should call alert function.

&lt;taconite&gt;
    &lt;alert&gt;Hello&lt;/alert&gt;
&lt;/taconite&gt;

will not work. because requrement of "select" is hard coded.

dependency on "select" should be removed.

following code is modifieid taconite that does it.

https://gist.github.com/936457

**Comment by leeoniya** [comment]
please edit and escape all HTML markup - it is invisible here.

**Comment by gops** [comment]
updated!!

**Comment by leeoniya** [comment]
what is the markup on the page? and what exactly are you setting the title of when not specifying a selector? every element on the page?

**Comment by gops** [comment]
that was just an example. my requirement was, able to call arbitrary function like alert. I have changed code that show that.

**Comment by leeoniya** [comment]
you call whatever you like using

<pre>
&lt;eval&gt;
  &lt;![CDATA[
    alert("Hello");
  ]]&gt;
&lt;/eval&gt;
</pre>
