### ISSUE TITLE
BUG: empty strings are converted to 0 

### ISSUE THREAD

**Issue by gops** [malsup/taconite#6]
a code like

``` html
<val select="textarea" arg1=""/>
```

is adding 0 to textarea value. 

It might be good idea to check length before converting to string.

so a code at line 262 should look like this

``` js
if(v.length){
var n = Number(v);
if (v == n) v = n;
}
```

instead of this.

``` js
var n = Number(v);
if (v == n){v = n;}
```

https://gist.github.com/936457

**Comment by malsup** [comment]
Good catch, thanks.  Fixed in v3.61.
